name: Tests

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: gd, pdo_sqlite, redis
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
        working-directory: src

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: src

      - name: Run Unit tests
        if: false # Set true to run tests
        run: php artisan test --testsuite=Unit
        working-directory: src

      - name: Run Feature tests
        if: false # Set true to run tests
        run: php artisan test --testsuite=Feature
        working-directory: src

      - name: Run PHPStan
        if: false # Set true to run tests
        run: composer phpstan
        working-directory: src

  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: build/test/Dockerfile
          ignore: "DL3018,DL4006,SC2028"
